export const STORAGE_KEY = "ai_todo_current_task_group";
export const DEVICE_ID_STORAGE_KEY = "ai_todo_device_id";

export const UI_TEXT = {
  APP_NAME: "AI Todo",
  APP_ROLE: "今日行动教练",
  HERO_TITLE: "今天想推进哪个目标？",
  APP_TAGLINE: "让 AI 帮你拆成今天能完成的小任务。",
  INPUT_CARD_TITLE: "生成今日行动计划",
  INPUT_CARD_DESCRIPTION: "输入一个目标，AI 会拆成 3-8 个可执行任务。",
  INPUT_PLACEHOLDER: "例如：我要学习 Python / 我要准备面试 / 我要做一个小项目",
  BUTTON_GENERATE: "生成今日任务",
  GENERATING_BUTTON: "生成中...",
  EMPTY_STATE_TITLE: "还没有生成今日任务",
  EMPTY_STATE_DESCRIPTION: "输入一个目标，让 AI 帮你拆出第一步。",
  TASK_LIST_TITLE: "今日行动计划",
  CLEAR_TASKS_BUTTON: "清空",
  REGENERATE_BUTTON: "重新生成",
  START_NEW_DAY_BUTTON: "开始新一天",
  NEW_DAY_PROMPT: "这是上次的任务，要开始新一天吗？",
  COMPLETE_ALL_TITLE: "🎉 今日任务已完成",
  COMPLETE_ALL_DESCRIPTION: "你已经把目标往前推进了一步。",
  LOADING_TEXT: "AI 正在拆解任务...",
  PRIVACY_NOTICE: "请勿输入密码、证件号等敏感信息。",
  EXAMPLE_LABEL: "不知道写什么？试试：",
  EXAMPLE_GOALS: [
    "我要学习 Python",
    "我要准备面试",
    "我要做一个小项目",
    "我要减肥",
  ],
} as const;

export const ERROR_MESSAGES = {
  EMPTY_INPUT: "请先输入一个目标。",
  INPUT_TOO_SHORT: "请输入更具体的目标，例如：我要学习 Python。",
  INPUT_TOO_LONG: "目标描述太长，请简化为一句话。",
  AI_GENERATION_FAILED: "任务生成失败，请稍后重试。",
  AI_PARSE_FAILED: "任务解析失败，请重新生成。",
  NETWORK_ERROR: "网络连接异常，请检查后重试。",
  SAVE_FAILED: "任务暂时无法保存，请稍后重试。",
  HIGH_RISK_INPUT:
    "这个目标可能会带来伤害或风险，我不能帮你拆解执行步骤。请换一个安全、积极的目标。",
  CHAT_INPUT: "我是用来帮你拆解任务的。请输入一个目标，例如：我要准备面试。",
  REGENERATE_FAILED: "重新生成失败，请稍后重试。",
  INVALID_DEVICE_ID: "设备标识无效。",
  INVALID_TASK_GROUP: "任务组数据无效。",
  NOT_CONFIGURED: "云端保存暂未配置。",
  CLOUD_SAVE_FAILED: "云端保存失败，请稍后重试。",
  CLOUD_LOAD_FAILED: "云端读取失败，请稍后重试。",
  CLOUD_DELETE_FAILED: "云端删除失败，请稍后重试。",
  AUTH_NOT_CONFIGURED: "登录服务暂未配置。",
  AUTH_OPERATION_FAILED: "登录操作失败，请稍后重试。",
} as const;

export const AUTH_TEXT = {
  LOGIN: "登录",
  LOGGED_IN: "已登录",
  LOGGING_STATUS: "登录状态...",
  LOGOUT: "登出",
  CLOSE: "关闭",
  MODAL_TITLE: "登录 AI Todo",
  MODAL_DESCRIPTION: "登录后可以多设备同步任务数据。",
  EMAIL_LABEL: "邮箱",
  EMAIL_PLACEHOLDER: "you@example.com",
  PASSWORD_LABEL: "密码",
  PASSWORD_PLACEHOLDER: "至少 6 位",
  CONFIRM_PASSWORD_LABEL: "确认密码",
  CONFIRM_PASSWORD_PLACEHOLDER: "再次输入密码",
  OTP_LOGIN_TAB: "验证码登录",
  PASSWORD_LOGIN_TAB: "密码登录",
  OTP_SEND_BUTTON: "发送验证码",
  OTP_SEND_LOADING: "发送中...",
  OTP_SENT_MESSAGE: "验证码已发送，请查看邮箱。",
  OTP_LABEL: "验证码",
  OTP_PLACEHOLDER: "输入 6 位验证码",
  OTP_VERIFY_BUTTON: "验证并登录",
  OTP_VERIFY_LOADING: "验证中...",
  OTP_RESEND_BUTTON: "重新发送",
  OTP_RESEND_COUNTDOWN: "重新发送",
  OTP_SWITCH_HINT: "已有密码？使用密码登录。",
  PASSWORD_LOGIN_BUTTON: "登录",
  PASSWORD_LOGIN_LOADING: "登录中...",
  PASSWORD_LOGIN_SWITCH_HINT: "没有密码？使用验证码登录。",
  SET_PASSWORD_TITLE: "设置登录密码",
  SET_PASSWORD_DESCRIPTION: "设置一个登录密码，下次可以更快登录。",
  SET_PASSWORD_BUTTON: "设置密码",
  SET_PASSWORD_LOADING: "保存中...",
  SET_PASSWORD_SKIP: "稍后再说",
  SET_PASSWORD_SUCCESS: "密码已设置。",
  EMAIL_REQUIRED: "请输入邮箱。",
  EMAIL_INVALID: "邮箱格式不正确。",
  PASSWORD_REQUIRED: "请输入密码。",
  PASSWORD_TOO_SHORT: "密码至少需要 6 位。",
  PASSWORD_MISMATCH: "两次输入的密码不一致。",
  OTP_REQUIRED: "请输入验证码。",
  OTP_INVALID_LENGTH: "请输入 6 位验证码。",
  OTP_INVALID: "验证码错误或已过期，请重新获取。",
  PASSWORD_LOGIN_ERROR: "邮箱或密码错误，请重试。",
  EMAIL_RATE_LIMITED: "操作过于频繁，请稍后再试。",
  FORGOT_PASSWORD_LINK: "忘记密码？",
  FORGOT_PASSWORD_TITLE: "忘记密码",
  FORGOT_PASSWORD_DESCRIPTION: "输入你的注册邮箱，我们会发送重置密码邮件。",
  FORGOT_PASSWORD_BUTTON: "发送重置密码邮件",
  FORGOT_PASSWORD_LOADING: "发送中...",
  FORGOT_PASSWORD_SUCCESS:
    "如果该邮箱已注册，重置密码邮件已发送。请查收邮件并点击重置链接。",
  FORGOT_PASSWORD_BACK: "返回登录",
  RESET_PASSWORD_TITLE: "设置新密码",
  RESET_PASSWORD_DESCRIPTION: "请输入你的新密码。",
  RESET_PASSWORD_NEW_PASSWORD_LABEL: "新密码",
  RESET_PASSWORD_CONFIRM_LABEL: "确认密码",
  RESET_PASSWORD_BUTTON: "重置密码",
  RESET_PASSWORD_LOADING: "重置中...",
  RESET_PASSWORD_SUCCESS: "密码已重置，请用新密码登录。",
  RESET_PASSWORD_TOKEN_EXPIRED: "重置链接已过期，请重新申请。",
  RESET_PASSWORD_TOKEN_INVALID: "重置链接无效，请重新申请。",
  RESET_PASSWORD_GO_LOGIN: "返回登录",
  RESET_PASSWORD_GO_FORGOT: "重新申请重置密码",
} as const;

